name: Artifacts Publish

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for inji-vci-client Updates'
        type: string
      publish:
        description: 'Publish kotlin or js'
        required: true
        default: 'Both[Kotlin and JS]'
        type: choice
        options:
          - kotlin
          - js
          - Both[Kotlin and JS]

jobs:
  maven-publish:
    if: ${{ inputs.publish == 'Both[Kotlin and JS]' || inputs.publish == 'kotlin'}}
    uses: mosip/kattu/.github/workflows/maven-publish-android.yml@master
    with:
      SERVICE_LOCATION: 'kotlin'
      ANDROID_SERVICE_LOCATION: 'vci-client'
      JAVA_VERSION: 21
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_URL: ${{secrets.OSSRH_SNAPSHOT_URL }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
  
  publish-to-npm-registry:
    if: ${{ inputs.publish == 'Both[Kotlin and JS]' || inputs.publish == 'js'}}
    uses: mosip/kattu/.github/workflows/npm-publish-to-npm-registry.yml@master
    with:
      SERVICE_LOCATION: 'js'
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
  
